version: '3.5'
services:
  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=my-rails-project_user
      - POSTGRES_DB=my-rails-project_development
      - POSTGRES_PASSWORD=my-rails-project_DBpassWord
      - POSTGRES_INITDB_ARGS="--username=my-rails-project_user"
      - DATABASE_URL=postgresql://my-rails-project_user:my-rails-project_DBpassWord@postgres:5432/my-rails-project
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/my-rails-project
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - POSTGRES_USER=my-rails-project_user
      - POSTGRES_DB=my-rails-project_development
      - POSTGRES_PASSWORD=my-rails-project_DBpassWord
      - DATABASE_URL=postgresql://my-rails-project_user:my-rails-project_DBpassWord@postgres:5432/my-rails-project
volumes:
   redis:
